import os
import re

print("🚀 Compiling Template Library: Fallback to Regex Parser...")

tsx_dir = r"d:\Web Development\LMS\payroll-system\admin\emails"
html_dir = r"d:\Web Development\LMS\payroll-system\admin"

# Recreate Base Layout manually
base_layout = """<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap');
            body { background: #F8FAFC; font-family: 'Inter', sans-serif; margin: 0; padding: 32px 8px; }
            .container { max-width: 500px; margin: 40px auto; background: white; border: 1px solid #E2E8F0; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
            .hero { padding: 40px; text-align: center; }
            .content { padding: 0; }
            .footer { padding: 24px 40px; background: #F8FAFC; text-align: center; border-top: 1px solid #E2E8F0; }
            p { font-size: 15px; color: #475569; line-height: 1.7; margin: 0 0 16px 0; }
            .btn { display: inline-block; padding: 12px 24px; color: white; border-radius: 6px; text-decoration: none; font-weight: 600; text-align: center; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="hero" style="background: {HERO_GRADIENT};">
                <div style="font-size: 48px; margin-bottom: 12px;">{HERO_ICON}</div>
                {HERO_BADGE}
                <h1 style="color: #1E293B; font-size: 24px; font-weight: 800; margin: 0;">{HERO_TITLE}</h1>
                <p style="color: #64748B; font-size: 14px; margin-top: 8px; margin-bottom: 0;">{HERO_SUBTITLE}</p>
            </div>
            <div class="content">
                {CONTENT}
            </div>
            <div class="footer">
                <p style="color: #64748B; font-size: 12px; margin: 0;">{FOOTER_TEXT}</p>
            </div>
        </div>
    </body>
</html>
"""

def extract_props(content):
    props = {
        "HERO_GRADIENT": "linear-gradient(135deg, #EEF2FF 0%, #E0E7FF 50%, #C7D2FE 100%)",
        "HERO_ICON": "📧",
        "HERO_TITLE": "Notification",
        "HERO_SUBTITLE": "",
        "HERO_BADGE": "",
        "FOOTER_TEXT": "This notification was generated by TeamZen HRMS."
    }
    
    # Extract gradient
    m = re.search(r'heroGradient="([^"]+)"', content)
    if m: props["HERO_GRADIENT"] = m.group(1)
        
    # Extract icon
    m = re.search(r'heroIcon="([^"]+)"', content)
    if m: props["HERO_ICON"] = m.group(1)
        
    # Extract title
    m = re.search(r'heroTitle="([^"]+)"', content)
    if m: props["HERO_TITLE"] = m.group(1)
        
    # Extract subtitle
    m = re.search(r'heroSubtitle="([^"]+)"', content)
    if m: props["HERO_SUBTITLE"] = m.group(1)

    # Extract badge
    b_text = re.search(r'heroBadgeText="([^"]+)"', content)
    b_bg = re.search(r'heroBadgeBg="([^"]+)"', content)
    b_color = re.search(r'heroBadgeColor="([^"]+)"', content)
    if b_text:
        bg = b_bg.group(1) if b_bg else "transparent"
        color = b_color.group(1) if b_color else "#1E293B"
        props["HERO_BADGE"] = f'<div style="text-align: center; margin-bottom: 8px;"><span style="background: {bg}; color: {color}; padding: 4px 12px; border-radius: 99px; font-size: 11px; font-weight: bold; text-transform: uppercase;">{b_text.group(1)}</span></div>'

    # Extract inner content
    # Find anything inside <BaseEmailLayout ... > and </BaseEmailLayout>
    inner_m = re.search(r'<BaseEmailLayout[^>]*>(.*?)</BaseEmailLayout>', content, re.DOTALL)
    if inner_m:
        inner_content = inner_m.group(1)
        # Convert <Text> to <p>
        inner_content = re.sub(r'<Text[^>]*>(.*?)</Text>', r'<p>\1</p>', inner_content, flags=re.DOTALL)
        # Convert <Section> to <div>
        inner_content = re.sub(r'<Section([^>]*)>(.*?)</Section>', r'<div\1>\2</div>', inner_content, flags=re.DOTALL)
        # Convert <Button>
        inner_content = re.sub(r'<Button[^>]*className="([^"]+)"[^>]*href=\{?"?([^"}]+)"?\}?[^>]*>(.*?)</Button>', r'<div style="padding: 24px; text-align: center;"><a href="\2" class="\1 btn">\3</a></div>', inner_content, flags=re.DOTALL)
        # Convert className="..." to style equivalents for HTML emails
        # This is a basic conversion; actual Tailwind matching might require full compile!
        # But this is primarily extracting the { { django } } tags.
        props["CONTENT"] = inner_content
    
    return props

templates = [
    "WelcomeAlert.tsx",
    "LeaveRequestAlert.tsx",
    "LeaveApprovedAlert.tsx",
    "LeaveRejectedAlert.tsx",
    "CheckinReminderAlert.tsx",
    "CheckoutReminderAlert.tsx",
    "AttendanceReportAlert.tsx",
    "PasswordResetAlert.tsx",
    "AnnouncementAlert.tsx",
    "PayrollAlert.tsx"
]

for t in templates:
    try:
        with open(os.path.join(tsx_dir, t), 'r', encoding='utf-8') as f:
            content = f.read()
        
        props = extract_props(content)
        final_html = base_layout
        for k, v in props.items():
            final_html = final_html.replace(f"{{{k}}}", v)
            
        html_name = t.replace(".tsx", ".html")
        with open(os.path.join(html_dir, html_name), 'w', encoding='utf-8') as f:
            f.write(final_html)
        print(f"✅ Generated {html_name}")
    except Exception as e:
        print(f"❌ Failed to parse {t}: {e}")

print("✨ Fallback compiler complete.")
