import {
    Body,
    Container,
    Head,
    Heading,
    Hr,
    Html,
    Preview,
    Section,
    Text,
    Tailwind,
} from '@react-email/components';
import React from 'react';

interface BaseEmailLayoutProps {
    previewText: string;
    heroGradient: string;
    heroIcon: string;
    heroTitle: string;
    heroBadgeText?: string;
    heroBadgeColor?: string;
    heroBadgeBg?: string;
    heroSubtitle?: string; // e.g. date under the title
    children: React.ReactNode;
    footerText?: string;
}

export const BaseEmailLayout = ({
    previewText,
    heroGradient,
    heroIcon,
    heroTitle,
    heroBadgeText,
    heroBadgeColor,
    heroBadgeBg,
    heroSubtitle,
    children,
    footerText = "This notification was generated by TeamZen HRMS."
}: BaseEmailLayoutProps) => {
    return (
        <Html>
            <Head />
            <Preview>{previewText}</Preview>
            <Tailwind>
                <Body className="bg-gray-50 font-sans my-auto mx-auto pt-8 px-2">
                    <Section className="border border-solid border-gray-200 rounded-lg my-10 mx-auto max-w-[500px] bg-white shadow-sm overflow-hidden" align="center">
                        {/* Hero Section */}
                        <Section className="px-[40px] pt-[40px] pb-[28px] text-center" style={{ background: heroGradient }}>
                            <Text className="text-[48px] leading-none m-0 mb-[12px]">{heroIcon}</Text>

                            {heroBadgeText && (
                                <Section className="text-center mb-[8px]">
                                    <Text
                                        className="px-3 py-1 rounded-full text-[11px] font-bold inline-block m-0 uppercase tracking-wide"
                                        style={{
                                            backgroundColor: heroBadgeBg || 'transparent',
                                            color: heroBadgeColor || '#1E293B'
                                        }}
                                    >
                                        {heroBadgeText}
                                    </Text>
                                </Section>
                            )}

                            <Heading className="text-[#1E293B] text-[24px] font-extrabold text-center p-0 m-0 tracking-tight">
                                {heroTitle}
                            </Heading>

                            {heroSubtitle && (
                                <Text className="m-0 mt-[8px] text-[14px] text-[#64748B]">
                                    {heroSubtitle}
                                </Text>
                            )}
                        </Section>

                        {/* Content Area */}
                        {children}

                        <Hr className="border border-solid border-gray-200 m-0 w-full" />

                        <Section className="px-[40px] py-[24px] bg-gray-50 text-center">
                            <Text className="text-[#64748B] text-[12px] leading-[24px] m-0">
                                {footerText}
                            </Text>
                        </Section>
                    </Section>
                </Body>
            </Tailwind>
        </Html>
    );
};

export default BaseEmailLayout;
