import {
    Body,
    Button,
    Container,
    Head,
    Heading,
    Hr,
    Html,
    Preview,
    Section,
    Text,
    Tailwind,
} from '@react-email/components';
import React from 'react';

// Using {{ variable }} syntax for Django templating after export
export const LeaveRequestAlert = () => {
    return (
        <Html>
            <Head />
            <Preview>Leave Request Update: {"{{"} status {"}}"}</Preview>
            <Tailwind>
                <Body className="bg-gray-100 font-sans my-auto mx-auto pt-8 px-2">
                    <Container className="border border-solid border-gray-200 rounded-lg my-10 mx-auto p-8 max-w-[500px] bg-white shadow-sm">
                        <Heading className="text-gray-900 text-[24px] font-bold text-center p-0 my-[10px] mx-0">
                            Leave Request <span className="uppercase text-blue-600">{"{{"} status {"}}"}</span>
                        </Heading>

                        <Text className="text-gray-800 text-[16px] leading-[24px] mt-6">
                            Hello {"{{"} managerName {"}}"},
                        </Text>

                        <Text className="text-gray-800 text-[16px] leading-[24px]">
                            The leave request for <strong className="text-black">{"{{"} employeeName {"}}"}</strong> has been updated.
                        </Text>

                        <Section className="bg-blue-50 border border-blue-100 p-6 rounded-md my-[24px]">
                            <Text className="text-blue-800 font-bold mb-2 uppercase tracking-wider text-xs">Details</Text>
                            <Text className="text-gray-800 m-0 leading-[24px]">
                                <strong>Dates Requested:</strong> {"{{"} dates {"}}"}
                            </Text>
                            <Text className="text-gray-800 m-0 leading-[24px] mt-2">
                                <strong>Current Status:</strong> <span className="uppercase font-bold text-black">{"{{"} status {"}}"}</span>
                            </Text>
                        </Section>

                        <Section className="text-center mt-[32px] mb-[32px]">
                            <Button
                                className="bg-black rounded-md text-white px-6 py-3 font-semibold no-underline text-center"
                                href="{{ dashboardUrl }}"
                            >
                                View in Dashboard
                            </Button>
                        </Section>

                        <Hr className="border border-solid border-gray-200 my-[26px] mx-0 w-full" />

                        <Text className="text-gray-500 text-[12px] leading-[24px]">
                            This notification was generated by TeamZen HRMS. Please do not reply directly to this email.
                        </Text>
                    </Container>
                </Body>
            </Tailwind>
        </Html>
    );
};

export default LeaveRequestAlert;
